version: "3"
services:
  db:
    build: ./db
    # restart: always
    environment:
      POSTGRES_DB: katekyo-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev_sample
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  back:
    build: ./back
    tty: true
    volumes:
      - ./back:/home/node/app/
      - ./.env:/home/node/app/.env
    ports:
      # prisma studio
      - 5555:5555
      - 8000:8000
    command: sh -c "yarn run start:dev"
    depends_on:
      - db
  front:
    build: ./front
    tty: true
    volumes:
      - ./front:/home/node/app/
      - ./.env:/home/node/app/.env.local
    ports:
      - 3000:3000
    command: sh -c "yarn run dev"
